services:
  postgres:
    image: postgres:15-alpine
    container_name: desterlib-postgres-test
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: desterlib_test
    ports:
      - "5433:5432" # Different port to avoid conflicts with main postgres
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_test_data:
