version: "3.8"

services:
  postgres:
    environment:
      POSTGRES_DB: desterlib_prod
    ports:
      - "5432:5432"

  api:
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/desterlib_prod?schema=public
    ports:
      - "3001:3001"
    # Remove volume mounts for production to use built container
    volumes: []
    # Use the default CMD from Dockerfile which runs the built application
    command: null
