import { EnvConfig } from "./env.js";

const DOCKER_IMAGE = "desterlib/api:latest"; // TODO: Update with your actual Docker Hub image

/**
 * Generate docker-compose.yml content
 */
export function generateDockerCompose(config: EnvConfig): string {
  return `# DesterLib Docker Compose Configuration
# Generated by DesterLib CLI

services:
  postgres:
    image: postgres:15-alpine
    container_name: desterlib-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${config.postgresUser}
      POSTGRES_PASSWORD: ${config.postgresPassword}
      POSTGRES_DB: ${config.postgresDb}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${config.postgresUser}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: ${DOCKER_IMAGE}
    container_name: desterlib-api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Required environment variables
      DATABASE_URL: ${config.databaseUrl}
      NODE_ENV: production
      PORT: ${config.port}
      
      # Rate limiting (optional - defaults shown)
      RATE_LIMIT_WINDOW_MS: 900000  # 15 minutes
      RATE_LIMIT_MAX: 100            # 100 requests per window
    ports:
      # Bind to all interfaces to allow mobile app connections
      - "0.0.0.0:${config.port}:${config.port}"
    volumes:
      # Mount your media library (read-only for security)
      - ${config.mediaPath}:/media:ro
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:${config.port}/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
    driver: local
`;
}

/**
 * Generate .env content
 */
export function generateEnvFile(config: EnvConfig): string {
  return `# DesterLib Configuration
# Generated by DesterLib CLI

# Database Configuration
DATABASE_URL=${config.databaseUrl}

# Server Configuration
NODE_ENV=production
PORT=${config.port}

# Rate Limiting (optional)
RATE_LIMIT_WINDOW_MS=900000  # 15 minutes in milliseconds
RATE_LIMIT_MAX=100           # Maximum requests per window

# Notes:
# - TMDB API key is configured in the app settings (not here)
# - JWT secret is stored in the database (not here)
# - Media path is configured in docker-compose.yml
`;
}

/**
 * Generate README for the installation directory
 */
export function generateReadme(port: number, installDir: string): string {
  return `# DesterLib Installation

This directory contains your DesterLib configuration.

## Quick Start

\`\`\`bash
# Start DesterLib
docker-compose up -d

# View logs
docker-compose logs -f

# Stop DesterLib
docker-compose down
\`\`\`

## Access Points

- **API Server**: http://localhost:${port}
- **API Documentation**: http://localhost:${port}/api/docs
- **Health Check**: http://localhost:${port}/health
- **WebSocket**: ws://localhost:${port}/ws

## Configuration Files

- \`docker-compose.yml\` - Docker services configuration
- \`.env\` - Environment variables and secrets

## Updating

To update to the latest version:

\`\`\`bash
# Pull latest image
docker-compose pull

# Restart with new image
docker-compose up -d
\`\`\`

## Reconfiguring

To change your configuration, run:

\`\`\`bash
desterlib
\`\`\`

## Useful Commands

\`\`\`bash
# View running containers
docker-compose ps

# Restart services
docker-compose restart

# View API logs
docker-compose logs -f api

# View database logs
docker-compose logs -f postgres

# Stop and remove everything (keeps data)
docker-compose down

# Stop and remove everything including data
docker-compose down -v
\`\`\`

## Troubleshooting

If you encounter issues:

1. Check logs: \`docker-compose logs -f\`
2. Verify containers are running: \`docker-compose ps\`
3. Restart services: \`docker-compose restart\`
4. Check port availability: \`lsof -i :${port}\`

For more help, visit: https://docs.dester.in
`;
}
